
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: farmsense-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: api.farmsense.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: farmsense-backend-svc
            port:
              number: 80
  - host: ml.farmsense.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: farmsense-ml-svc
            port:
              number: 80
  - host: app.farmsense.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: farmer-dashboard-svc
            port:
              number: 80
